export { default as About } from './about/about'
export { default as Contact } from './contact/contact'
export { default as Email } from './email/email'
export { default as Featured } from './featured/featured'
export { default as Footer } from './footer/footer'
export { default as Graphic } from './graphic/graphic'
export { default as Hero } from './hero/hero'
// export { default as Jobs } from './jobs/jobs';
export { default as Layout } from './layout'
export { default as Logo } from './logo'
export { default as Menu } from './menu/menu'
export { default as Nav } from './nav/nav'
export { default as Post } from './post/post'
export { default as Projects } from './projects/projects'
export { default as SEO } from './seo'
export { default as Side } from './side/side'
export { default as Social } from './social/social'
